version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: quartz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-quartz.sql:/docker-entrypoint-initdb.d/init-quartz.sql


volumes:
  postgres_data:
