version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: yourStrong(!)Password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init-sql-server-quartz.sql:/docker-entrypoint-initdb.d/init-quartz.sql

volumes:
  mssql_data:
